### ISSUE TITLE
Unknown problem is a null pointer exception caused by a missing null check

### ISSUE THREAD

**Issue by mendess** [yWorks/yGuard#101]
https://github.com/yWorks/yGuard/blob/00e10b5b62c84aca0e2138e0ca12a702f8dc0abf/src/main/java/com/yworks/yshrink/core/Writer.java#L109-L110

`cd` can be null which will cause a null pointer exception and consequently a unhelpful `yShrink encountered an unknown problem!` diagnostic.

Checking and throwing a more informative exception, with the name of the unmodeled class would help troubleshoot the issue. I have personally encountered this and it's making it hard to understand what I miss configured.

**Comment by Fohlen** [comment]
@mendess thanks for opening this ticket. I don't entirely understand how a class that's read from a JAR would become unmodelled inside the shrinker in this scenario. Can you share a test case with us so we can find a concise solution to this problem. All the best

**Comment by yGuy** [comment]
Closing because of missing feedback.
