### ISSUE TITLE
Digests for resources in rename task

### ISSUE THREAD

**Issue by TimurDaas** [yWorks/yGuard#102]
Hello.
I found out that property `digests` is ignored while processing resource files(e.g lang.properties) in rename task. It always uses two default hash algorithms: MD5 & SHA. Both of them are deprecated.
In shrink task - it works good. Property is not ignored.
It is not correct because OpenJDK(I tried in Linux) while checking JAR signature also checks MANIFEST.MF file and detects week hashing algorithm. In Java disabled algorithms are setted in property jdk.jar.disabledAlgorithms in java.security file.

If I`m not correct, please, explain me why...

**Comment by thomasbehr** [comment]
You are right, the `digests` property is currently ignored for resource files. Unfortunately, there is no workaround for this problem.

**Comment by TimurDaas** [comment]
I can create pull request with fix, if you need my help?

**Comment by TimurDaas** [comment]
Fixed. Changes will be able in future releases

**Comment by pietroSV** [comment]
> Fixed. Changes will be able in future releases

Hi. When will new release be available? Thanks
