### ISSUE TITLE
Add Spring Boot with Gradle example

### ISSUE THREAD

**Issue by soprabaixar2** [yWorks/yGuard#105]
I tried to adapt it with the examples you have here, but spring boot by default when running the build of Gradle it generates 2 jar (app.jar and app-plain.jar).

The app.jar works but the app-plain.jar does not work and yGuard generates the obfuscated file based on the app-plain.jar. I tried to force it to generate an obfuscated as the base of the app.jar but it gives an error.

Could you just show a simple example using Spring Boot with Gradle?

**Comment by thomasbehr** [comment]
Please see the [processing example](https://github.com/yWorks/yGuard/tree/master/examples/processing) and the [Yguard Obfuscation in a Spring Boot Project](https://github.com/yWorks/yGuard/issues/43) topic for further information on obfuscation Spring Boot applications.
