### ISSUE TITLE
Update yGuard to work with Java 15

### ISSUE THREAD

**Issue by thomasbehr** [yWorks/yGuard#108]
- Check if Java 15's javac produces invokeconstant byte code instructions for plain Java source code.
(If yes, postpone until #86 is done.)
- Check if there are invokeconstant byte code instructions in Java 15's runtime library.
(If yes, postpone until #86 is done.)
- Check if ASM supports Java 15 byte code. (If no, update ASM.)
- Increase the class file version supported by yGuard.

It is not necessary to support Java 15 preview features such as records or sealed class as part of this issue.

See [Oracle's Java 15 announcement](https://www.oracle.com/de/news/announcement/oracle-announces-java-15-2020-09-15.html) for all new features.

**Comment by sgaurav37533** [comment]
Hello can you please assign me this issue I can take care of it.

**Comment by Vampire** [comment]
What about Java 17?

**Comment by thomasbehr** [comment]
I am currently investigating the first point of this issue. I do believe that javac will not create CONSTANT_Dynamic byte code instructions when compiling Java source code, since there are not such instructions in the runtime libraries of Java 15, 16, and 17. If I am right, all there is to do is updating ASM and increasing the supported class file version. In short, Java 15 support will be ready soon.

Supporting Java 16 and Java 17 on the other hand, will require a bit more implementation work due to new language features (records and sealed classes). While we do plan to support Java 16 and Java 17, I do not know yet how much work this will be and thus how long it will take.
