### ISSUE TITLE
Unsupported class file major version 61

### ISSUE THREAD

**Issue by jeancc** [yWorks/yGuard#110]
I'm trying to obfuscate code compiled with openjdk 17, using yguard 3.0.0. It seems that openjdk 17 is not suported:

Ant output:

[shrink] ERROR: Unsupported class file major version 61
[shrink] Unsupported class file major version 61

**Comment by thomasbehr** [comment]
Correct, yGuard does not support Java 17 byte code. See [Compatibility](https://yworks.github.io/yGuard/compatibility/) in the [yGuard documentation](https://yworks.github.io/yGuard/).

**Comment by jeancc** [comment]
I've tried to change 'Compiler compliance level' on eclipse IDE to 11, with no luck...

**Comment by thomasbehr** [comment]
Actually use a Java 11 compiler to compile your source code to Java 11 byte code instead of asking a higher version compiler to produce lower version byte code.
