### ISSUE TITLE
Spring-boot war obfuscation 

### ISSUE THREAD

**Issue by thesherrinford** [yWorks/yGuard#126]
spring boot obfuscated war deletes springframework directory despite of using external library attribute.
moreover, manifest.mf file contents are getting replaced despite of mentioning the opposite in adjust attribute.

**Comment by Fohlen** [comment]
Could you add a minimal example with a POM or Gradle to reproduce? You should assume that collaborators of this project do not necessarily know Spring Boot.

**Comment by thesherrinford** [comment]
it's a maven project, so pom.xml
PFA dependencies and plugin attributes.

**Comment by thomasbehr** [comment]
Photos of your screen do not qualify as short, self-contained example **that lets us reproduce the problem**. Unless you can provide such an example (in the case of Maven that means a **standalone pom.xml**), we will not even try to look into your problem.

**Comment by thesherrinford** [comment]
apologies!
- PFB the pom.

https://drive.google.com/file/d/1HBhtN6DGFq_MKFqxu0O4FpzgxtSsALBT/view?usp=drivesdk

**Comment by thesherrinford** [comment]
apologies!
- PFA the pom.

https://drive.google.com/file/d/1HBhtN6DGFq_MKFqxu0O4FpzgxtSsALBT/view?usp=drivesdk

**Comment by thesherrinford** [comment]
hi!
any update please.

**Comment by thomasbehr** [comment]
When I run one of the Maven goals for your pom.xml, Maven tells me "No sources to compile". I.e. it is not possible to reproduce the problem. And thus it is not possible to determine the cause for the problem either.

That said, yGuard does not support WAR files. It supports JAR files only.

**Comment by thesherrinford** [comment]
gimme some time, I'll upload the whole project in a repository and share.
Actually I've been able to get two wars, normal output and an obfuscated one. I'll help you replicate the issue.

**Comment by yGuy** [comment]
No. Do not upload the whole project. If you upload, upload a minimal example. Otherwise no one will want to spend their free time on this.
