### ISSUE TITLE
Keep method params

### ISSUE THREAD

**Issue by Fargys1879** [yWorks/yGuard#138]
How configure in gradle to keep method params?

**Comment by thomasbehr** [comment]
yGuard does not remove method parameters. If shrinking is enabled (which I recommend against), yGuard may remove unused methods but not individual parameters. If only renaming is enabled (but no shrinking), only certain attributes like LineNumberTable are removed but no method parameters. (Which attributes are removed may be configured using the [attributes](https://yworks.github.io/yGuard/task_documentation.html#the-attribute-element) element.)

**Comment by Fargys1879** [comment]
The problem is that it renames the parameters.Is it possible to somehow prohibit renaming parameters?

**Comment by thomasbehr** [comment]
Actually, yGuard does not rename method parameters, but it does remove the LocalVariableTable attribute by default (and I think parameter names are stored in said attribute). If you want to retain the LocalVariableTable attribute, configure your obfuscation task appropriately (using the [attribute](https://yworks.github.io/yGuard/task_documentation.html#the-attribute-element) element I mentioned in my previous comment).

**Comment by Fargys1879** [comment]
Thank's! It Solve my problem
`keep {
                    'attribute'(
                            name: 'MethodParameters'
                    )......`
