### ISSUE TITLE
How to obfuscate .apk with this tool?

### ISSUE THREAD

**Issue by Dazmed707** [yWorks/yGuard#143]
Tutorial for obfuscate apk?
support for apk files?

**Comment by Fohlen** [comment]
Hi, I'm not exactly sure this question makes sense. How do you produce your APK?

According to [Android Studio](https://developer.android.com/build/shrink-code), the gradle plugin already performs obfuscation and shrinking via the R8 compiler. In this case, running yGuard is unnecessary.

If you produce your APK in a different way you could study the [processing example](https://github.com/yWorks/yGuard/tree/master/examples/processing) for inspiration.
