### ISSUE TITLE
What are the limitations of yGuard tool ?

### ISSUE THREAD

**Issue by Shalaka1197** [yWorks/yGuard#148]

**Comment by Shalaka1197** [comment]
Is this supports Java ,Spring boot and maven project ?

**Comment by thomasbehr** [comment]
Yes, see #136 , see examples.

**Comment by thomasbehr** [comment]
Yes, see #136 , see [examples](https://github.com/yWorks/yGuard/tree/master/examples).

**Comment by yGuy** [comment]
There are no limitations that aren't documented. Feel free to report any findings that you feel aren't documented.
Other than this, please stop spamming the issue list with consultancy requests. This is for specific issues, not a general discussion.
