### ISSUE TITLE
How to found main class after yGuard Obfuscation ?

### ISSUE THREAD

**Issue by hacimertgokhan** [yWorks/yGuard#160]
Hello, I am minecraft plugin developer that using java.
Is there any way that we can easily find what is the new main class path ? 
Plugin cannot load without main class.

Thank you.

**Comment by Fohlen** [comment]
You can use the keep element. https://github.com/yWorks/yGuard/blob/master/examples/application/build.gradle#L49
You can specify which classes not to rename and that should do.
