### ISSUE TITLE
Is it possible to revert code obfuscation to recover source code?

### ISSUE THREAD

**Issue by jesussuarz** [yWorks/yGuard#162]
Is there any way to revert the changes?

I have obfuscated my code and, by mistake, I lost all of my original source code. Now I am trying to recreate everything from scratch. The easiest approach was to decompile the JAR file, but many things have changed in the generated code.

I would like to ask if there is any way to reverse the obfuscation process to recover the original code.

I would greatly appreciate any help.

Thank you.

**Comment by Fohlen** [comment]
If you have the obfuscation log file you can recreate the original package structure and method names, but variable names are lost for sure. It’s possible to recreate some code by hand but it is a lot of work. To sum up your question: no it’s not possible. Please don’t lose the source code to your obfuscated project 😃
