### ISSUE TITLE
Yguard Obfuscation in a Spring Boot Project

### ISSUE THREAD

**Issue by angelsinistanbul** [yWorks/yGuard#43]
Let me ask you something. Have a an application that is written on spring boot. To obfuscate the jar via yguard, i have no success that i would like to exclude BOOT-INF/lib folder. Could you help me on it?

Thanks a lot.

**Comment by Fohlen** [comment]
Hey @angelsinistanbul 
Please have a look at the `resources` demo. You can use the `adjust` block to prevent renaming / shrinking of your `BOOT-INF` folder. See https://github.com/yWorks/yGuard/blob/master/examples/resources/pom.xml#L55

**Comment by angelsinistanbul** [comment]
I have tried the example. However, i could not make it. If you would like to try it via spring-boot-maven-plugin, i am pretty sure that you wont make it. By the way, i have been trying to obfuscate the jar for 2 weeks :)

**Comment by yGuy** [comment]
You are "pretty sure that we won't make it"? I guess we should not even try, then.
What makes you think so? We can't even tell whether you even tried. You could have at least shared your configuration and told us where you struggled.

**Comment by Fohlen** [comment]
@angelsinistanbul could you please provide a sample including: 

1) your `pom.xml` (or other config) 
2) a description of what exactly you are trying to do and how it can be reproduced

You can also upload a test case for your project here (as a pull request or as a zip archive in the issue section). This way we can avoid future problems with setting up `yGuard` and Spring Boot.

**Comment by neil-benn** [comment]
Hello,

  I'd like to pick this up because I'm doing the same thing but I am 'pretty sure we will make it'!  The issue is that the BOOT-INF contains two sets of resources.  The first is the class files; this is the actual application and this is what needs to be obfuscated and the second is the lib directory which doesn't.  Running a 'vanilla' obfuscate has the problem that yGuard thinks that the package name is BOOT-INF.com.blah.blah whereas it is com.blah.blah.  Can we tell yGuard that the files it needs are in BOOT-INF and to use this as the base directory to obfuscate not the root directory of the jar?

  Thanks; BTW when I've finished - I'll be more than happy to contribute my build.xml file back as an example.

Cheers,

Neil

**Comment by Fohlen** [comment]
@neil-benn it would be good if you could create a test case in the `examples` folder. This way I can also check it out locally. 

Do the issues still occur when disabling the shrinker? We are aware of some issues with lambdas and the shrinker in Java 10+ and will be fixing them asap.

**Comment by neil-benn** [comment]
Thanks for your response.  I can't easily put up unobfuscated code to demonstrate it so an example is a bit tricky but I can look into it.  What I've got right now is that in the unobfuscated jar; the top directory is:

BOOT-INF
META-INF
org (this contains the spring code

After obfuscation I have:

A
B
BOOT-INF (this contains the dependent libs and unobfuscated code)
com (this contains obfuscated code)
META-INF
org

After obfuscation the obfuscated code is not put back in the boot directory and thea unobfuscated code is still left there.

My yguard task is:

<yguard>
	<inoutpair in="${dp5.jar.file}.ziath" out="${dp5.jar.file}.obs" />
	<rename mainclass="com.ziath.datapaq5.Datapaq5Application" logfile="renamelog.xml">
		<property name="language-conformity" value="illegal" />
		<property name="naming-scheme" value="mix" />

		<keep>
			<class classes="private" methods="private" fields="private">
				<patternset>
					<include name="org.**" />
					<exclude name="com.ziath.**" />
				</patternset>
			</class>
		</keep>
	</rename>
</yguard>

  So I don't think I'm shrinking unless I specifically need to exclude it?  The base issue is that I need to tell yGuard that the code is in BOOT-INF/classes and to obfuscate that and then put it back.  Is that possible?

Cheers,

Neil

**Comment by neil-benn** [comment]
I'm addition; interestingly even though I'm excluding org.** yGuard is still obfuscating the org.springframework.** classes.  These are not in BOOT-INF but in the root of the jar so they should be excluded?

**Comment by neil-benn** [comment]
OK; I've done some more work.  The yguard task now is:

```
<yguard>
	<externalclasses>
		<fileset dir="${unzip.dir}/BOOT-INF/lib/">
			<include name="*.jar"/>
		</fileset>
	</externalclasses>
	<inoutpair in="${dp5.jar.file}.ziath" out="${dp5.jar.file}.obs" />
        <rename mainclass="com.ziath.datapaq5.Datapaq5Application" logfile="renamelog.xml">
        	<property name="language-conformity" value="illegal" />
		<property name="naming-scheme" value="mix" />
        	<keep>
			<class classes="private" methods="private" fields="private">
				<patternset>
					<include name="org.**" />
					<exclude name="com.ziath.**" />
				</patternset>
			</class>
		</keep>
	</rename>
</yguard>
```
Now I've properly referenced the external classes in my jars; I've got the root of the obfuscated jar looking like:

BOOT-INF
com
META-INF
org

  Now the original code has been removed from BOOT-INF but the unobfuscated code is still at the top level - I still need this in the BOOT-INF.  I could break the jar open and just move the code into the right place and then zip it back up again but I'm not sure that is going to work.  Can you provide a comment on that, please? 

  Thanks; I'll obviously write this up for the community; I've still got exclusions to make to get spring-boot working after this!

Cheers,

Neil

**Comment by thomasbehr** [comment]
You are on the right track here:
Move your code into a "regular" jar (i.e. no code in BOOT-INF), obfuscate the regular jar, repackage the obfuscated jar for Spring Boot (i.e. jar with code in BOOT-INF).

**Comment by angelsinistanbul** [comment]
I guess my question that I asked you all, is not a question, It should be a bug?

**Comment by thomasbehr** [comment]
Spring deliberately packages code in a non-standard way - "non-standard" as in "BOOT-INF is not part of the JAR specification", see [JAR File Specification](https://docs.oracle.com/en/java/javase/13/docs/specs/jar/jar.html).
yGuard does not support this non-standard packaging. You might call it a missing feature, but it is not a bug.

**Comment by neil-benn** [comment]
I agree that it is not a bug at all; Spring Boot does weird things!  I'll work up an ant script to do what you suggested and then make a minimised version and drop it in the examples if you'd like me to do that?

**Comment by Fohlen** [comment]
@neil-benn that would be nice! We can add it to the `examples` folder. I can also port the example to `Maven` and `Gradle` so it will be available for the wider community. All the best.

**Comment by Fohlen** [comment]
@angelsinistanbul and @neil-benn, please have a look at the [processing example](https://github.com/yWorks/yGuard/tree/master/examples/processing). It obfuscates a spring boot application.

**Comment by neil-benn** [comment]
Hello,

 Thanks, I've done it all in ant and I'm just finishing it off as there are
a lot of what ifs.  When I've done that I'll strip it out to give an
example and submit it to yguard.  However I've been pulled onto other
matters for a short while.

Cheers,

Neil
