### ISSUE TITLE
yGuard Documentation ~ Broken Link "Task documentation"

### ISSUE THREAD

**Issue by KiraResari** [yWorks/yGuard#55]
I stumbled across a broken link in the yGuard Documentation, leading me to the following partially non-existent page.

https://yworks.github.io/yGuard/task

How I got there:

1. On the github page of yGuard (https://github.com/yWorks/yGuard), in the  README.md section, under "Usage" click on the link "is available" in the sentence "An online version of this documentation is available."
2. This will open the yGuard Documentation (https://yworks.github.io/yGuard/). There, under "Table of contents" in the main body of the page, click on the link "Task documentation"
3. This will open the page https://yworks.github.io/yGuard/task . which apart from a navigation only has a 404 error.

Notably, I am able to reach the Task Documentation by using the sidebar navigation, which will take me to the page https://yworks.github.io/yGuard/task_documentation/

I thus suppose that the link in the table of contents should be pointing to
https://yworks.github.io/yGuard/task_documentation/
instead of 
https://yworks.github.io/yGuard/task

**Comment by KiraResari** [comment]
Some of the other links in the body table of content seem to be outdated too.

For example, the link on "Using `Gradle`" points to:
https://yworks.github.io/yGuard/setup/#installation-using-gradle
...instead of the correct anchor:
https://yworks.github.io/yGuard/setup/#setup-using-gradle

**Comment by Fohlen** [comment]
Thanks for the heads up, I will fix these asap
