### ISSUE TITLE
Annotation @Obfuscation causes error: package com.yworks.util.annotation does not exist

### ISSUE THREAD

**Issue by KiraResari** [yWorks/yGuard#56]
Based on this documentation page: https://yworks.github.io/yGuard/task_documentation/#controlling-obfuscation-exclusion-with-annotations

...I am trying to exclude the main function of my class from Obfuscation using:
```
  @com.yworks.util.annotation.Obfuscation( exclude = true, applyToMembers = false)
  public static void main(String[] args) {
    try {
      new Start();
    } catch (SQLException e) {
      LOGGER.error(e, e);
    }
  }
```

My IDE (Eclipse 2019-14) apparently believes that package path to be valid, since it does not show an error.

However, when I try to Gradle build the project, I get the following error:
```
...\Start.java:22: error: package com.yworks.util.annotation does not exist
  @com.yworks.util.annotation.Obfuscation( exclude = true, applyToMembers = false)
                             ^
```

In my build.gradle, I only import the following from yGuard:
```
	compile 'com.yworks:yguard:2.9.2'
```

I don't know the dependency tree, or where I would get the com.yworks.util.annotation package from. I have tried various approaches, but most of them made it only worse.

At best, I am doing something wrong, in which case I would be grateful if the documentation about how to use these annotations could be made clearer.

At worst, something is broken right now and the @Obfuscation Annotation is not working.

**Comment by KiraResari** [comment]
As a workaround, I now created my own annotation class in the project, as described in the documentation:

```
package com.company.project.module.annotations;

public @interface Obfuscation {
	  boolean exclude() default true;

	  boolean applyToMembers() default true;
}
```

...and then included it in the gradle task as following:

```
task yGuardObfuscate {
	group 'yGuard'
	description 'Obfuscates existing archives.'
	dependsOn "installDist"

	doLast {
		ant.taskdef(
			name: 'yguard',
			classname: 'com.yworks.yguard.YGuardTask',
				classpath: sourceSets.main.runtimeClasspath.asPath
			)
		
		ant.yguard {
			inoutpairs {
				fileset(dir: "./build/install/module") {
					include(name: "module*.jar")
					exclude(name: "*_obf.jar")
				}
			}
			
			rename(logFile: "./build/install/module/rename.log", annotationClass: "com.company.project.module.annotations.Obfuscation") {
				property(name: "naming-scheme", value: "mix")
			}
		}
	}
}
```

**Comment by thomasbehr** [comment]
The Obfuscation class is in a separate jar (which is mentioned in the documentation you linked to above). As a result, you need to add an additional compile dependency to your gradle script:
```
compile 'com.yworks.annotation:2.9.+
```
Please see this [gradle script](https://github.com/yWorks/yGuard/blob/master/examples/annotation/build.gradle) for an example.

**Comment by KiraResari** [comment]
I see. Thanks for thin information. =^,^=

Could you please add this to the documentation? It would be a really valuable advice for people like me who only have a year or so experience in Gradle and are not yet familiar with all the implications.

**Comment by KiraResari** [comment]
Umm, I tried this now, but it gave me the following error while trying to build:

```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.yworks.annotation:2.9.+:.
```

for

```
	compile 'com.yworks:yguard:2.9.2'
	compile "com.yworks.annotation:2.9.+"
```

I also tried this, but it also didn't work:

```
	compile 'com.yworks:yguard:2.9.2'
	compile "com.yworks.annotation:2.9.2"
```

This caused the error to become:

```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.yworks.annotation:2.9.2:.
```

@thomasbehr : Sorry, but could you please re-open this? It seems to me like this is not solved just yet.

**Comment by thomasbehr** [comment]
Sorry, there was a typo in my first answer: Exactly as in the yguard dependency there has to be a colon right before `annotation` not a dot. It is corrected now.

**Comment by KiraResari** [comment]
Thanks! Now it works!

I am reasonably sure there also needs to be a ' behind the entire statement, but that one was obvious enough for me to figure out.

Just out of interest, was there any possible path for me to get from the `com.yworks.util.annotation.Obfuscation` mentioned in the documentation to the `compile "com.yworks:annotation:2.9.2"`? I've been trying to search the Maven Repository, and now that I know where that package lies I can find it there too, but without knowing the exact address, I couldn't find it.
