### ISSUE TITLE
ERROR: Illegal char <:> in jar shrinking

### ISSUE THREAD

**Issue by rob-daneel** [yWorks/yGuard#62]
Hello,

I'm using the latest version of yGuard to shrink and rename (obfuscate) a jar archive. I created an ant script (see the file "build.xml" in the attached zip - the user name in the paths is substituted with some asterisks) using the latest version of Eclipse with the JDK11 on Windows 10, but the shrink operation fails with the message reported in the object (see also the file "yshrinklog.xml"). It seems that yguard interprets uncorrectly the Windows path (as a Unix path? - see the prepended slash). For uploading problems  the zip is protected with password "password".

Any ideas?

[docs.zip](https://github.com/yWorks/yGuard/files/4872361/docs.zip)
[Issue62.zip](https://github.com/yWorks/yGuard/files/4902547/Issue62.zip)

**Comment by Fohlen** [comment]
Hello @rob-daneel 
I seem to be unable to open `docs.zip` with the provided password.
Alternatively you may use https://dpaste.org/ or a similiar service to attach logs here.
All the best,

Lennard

**Comment by rob-daneel** [comment]
> 
> 
> Hello @rob-daneel
> I seem to be unable to open `docs.zip` with the provided password.
> Alternatively you may use https://dpaste.org/ or a similiar service to attach logs here.
> All the best,
> 
> Lennard

Hello again,

the link for build.xml: https://dpaste.org/22MJ
the link for yshrinklog.xml: https://dpaste.org/hVPi

Best regards.

**Comment by ilpersi** [comment]
I have the same issue. Have you been able to reproduce this or you need more input?

**Comment by awoolfe** [comment]
Same issue here (Windows PC):

> Illegal char <:> at index 2: /C:/Users/......

**Comment by Fohlen** [comment]
The corresponding changes will land in upstream yGuard with the next version. Cheers 🍻
