### ISSUE TITLE
Question: how do I make sure that packaged dependencies are not stripped out from the obfuscated jar?

### ISSUE THREAD

**Issue by ilpersi** [yWorks/yGuard#71]
First of all let me compliment you for this amazing tool.

I have the following question: I am packaging my Java jar with Maven and the `maven-assembly-plugin` with the `jar-with-dependencies configuration` this makes it so that all the required dependencies are packaged as part of my final jar.

When I try to obfuscate this jar using yGuard all the packed dependencies are stripped out and thus the resulting jar is not working properly: how can I address this?

Based on my understanding of the documentation this should be managed with the `externalclasses` element and I have not been able to make it work correctly. Can I get some help with this? Below is my current configuration.

Thank you.

```
<target>
	<property name="compile_classpath" refid="maven.compile.classpath"/>
	<property name="runtime_classpath" refid="maven.runtime.classpath"/>
	<property name="test_classpath" refid="maven.test.classpath"/>
	<property name="plugin_classpath" refid="maven.plugin.classpath"/>

	<taskdef name="yguard" classname="com.yworks.yguard.YGuardTask" classpath="${runtime_classpath}"/>
	<yguard>
		<!-- see the yGuard task documentation for information about the <yguard> element-->
		<inoutpair in="${project.build.directory}/${project.build.finalName}.jar" out="${project.build.directory}/obfuscated.jar" resources="copy" />

		<rename  mainclass="com.github.ilpersi.BHBot.BHBot" logfile="${basedir}/yguard.log.xml"
				 replaceClassNameStrings="true">
		</rename>
		<externalclasses>
			<pathelement path="${runtime_classpath}" />
		</externalclasses>
	</yguard>
</target>
```

**Comment by Fohlen** [comment]
Hello there @ilpersi 
This sounds like you are using the `shrink` element. You may use whitelists to ignore these classes using the [keep](https://yworks.github.io/yGuard/task_documentation/#the-keep-element) element.

**Comment by ilpersi** [comment]
I @Fohlen, currently I am not using shrink because of #62 so somehow the obfuscated jar is shrunk anyway even if no `shrink ` element is present in the configuration. Is that even possible?

**Comment by Fohlen** [comment]
@ilpersi can you try to replicate this with a minimal set of code? Of the top of my head I cannot think of any way that the `rename` task would strip classes (in fact, I don't even think it is capable of doing so). This seems like undesired behaviour / a fatal bug.

**Comment by ilpersi** [comment]
Hi @Fohlen, I can try to set up a minimal boilerplate to reproduce this.

Before you post I went a bit further with this: as I see that #62 is fixed in the master branch, I cloned it and pointed my maven to the latest compiled jar so that I can also test with the shrink configuration.

Now I have the following task XML

```
<target>
	<property name="compile_classpath" refid="maven.compile.classpath"/>
	<property name="runtime_classpath" refid="maven.runtime.classpath"/>
	<property name="test_classpath" refid="maven.test.classpath"/>
	<property name="plugin_classpath" refid="maven.plugin.classpath"/>

	<taskdef name="yguard" classname="com.yworks.yguard.YGuardTask" classpath="${runtime_classpath}"/>
	<yguard>
		<!-- see the yGuard task documentation for information about the <yguard> element-->
		<inoutpair in="${project.build.directory}/${project.build.finalName}.jar" out="${project.build.directory}/BHBot_obfuscated.jar" resources="copy" />
		<shrink logfile="shrinklog.xml">
			<keep>
				<!-- single entrypoint: main method -->
				<method name="void main(String[] args)" class="com.github.ilpersi.BHBot.BHBot" />
				<class>
					<patternset>
						<include name="afu.*"/>
						<include name="javax.*"/>
					</patternset>
				</class>
			</keep>
		</shrink>
		<rename  mainclass="com.github.ilpersi.BHBot.BHBot" logfile="${basedir}/yguard.log.xml"
				 replaceClassNameStrings="true">
			<keep>
				<package>
					<patternset>
						<include name="afu.*"/>
						<include name="javax.*"/>
					</patternset>
				</package>
			</keep>
		</rename>
		<externalclasses>
			<pathelement path="${runtime_classpath}" />
		</externalclasses>
	</yguard>
</target>
```

As you can see below, comparing the two decompiled jars, all the classes are stripped and the keep element seems to be ignored.

![image](https://user-images.githubusercontent.com/43588107/93194826-ce5b0900-f748-11ea-807b-4f05bc485f1b.png)

Thank you.

**Comment by ilpersi** [comment]
Hi @Fohlen and sorry for double posting.

As mentioned before I've set-up a [simple boilerplate](https://github.com/yWorks/yGuard/issues/71) to reproduce this.

It is basically a "Hello World" example, using a single dependency (log4j2) and built with the technique explained in my first post.

If you use IntelliJ, using the Maven integration, it will be quite easy to set it up and package it.

Hope this helps.

**Comment by yGuy** [comment]
This one:
````
package>
					<patternset>
						<include name="afu.*"/>
						<include name="javax.*"/>
					</patternset>
				</package>
```` 
Should probably be this:
````
package>
					<patternset>
						<include name="afu.**"/>
						<include name="javax.**"/>
					</patternset>
				</package>
```` 
Note the duplicated `*` which have a different meaning in Ant - your rules tells yguard to keep all classes which are directly in javax and afu, but *not* nested inside, I guess. Please try and see if this changes anything.

**Comment by yGuy** [comment]
> I @Fohlen, currently I am not using shrink because of #62 so somehow the obfuscated jar is shrunk anyway even if no `shrink ` element is present in the configuration. Is that even possible?

You are using "keep" which is basically the same as "shrink", so without the "keep" all should be fine.

**Comment by ilpersi** [comment]
@yGuy 
- using `**` does not solve the issue (I also reproduced this in the boilerplate I linked before)
- for #62 I solved compiling from the master branch and pointing Maven to my compiled .jar so I can use shrink without issues.

**Comment by ilpersi** [comment]
@Fohlen @yGuy have you been able to reproduce this?

**Comment by Fohlen** [comment]
Unfortunately I was unable to reproduce this. If you wish to resolve this issue please try to:

- create a minimal `pom.xml` leveraging the `3.0.0-SNAPSHOT` from the current master branch
- create some pseudo-code consumed by your `pom.xml`
- attach these files as an archive to the ticket

If we can reproduce your issue this way, we can help you write a config / fix potential bugs.
All the best

**Comment by ilpersi** [comment]
@Fohlen I created what you ask [here](https://github.com/ilpersi/yGuar-boilerplate). Unfortunately in my previous comment the link was wrong.

It is basically a "Hello World" example, using a single dependency (log4j2) and built with the technique explained in my first post.

If you use IntelliJ, using the Maven integration, it will be quite easy to set it up and package it and get the issue reproduced.

Hope this helps.

**Comment by Fohlen** [comment]
Hey there @ilpersi 
I have checked out your repository and noticed a few problems right away:

```xml
<inoutpair in="${project.build.directory}/${project.build.finalName}.jar" out="${basedir}/obfuscated.jar" resources="copy" />
```

Does **exactly** what it is supposed to. It will obfuscate the `yGuar-boilerplate-1.0-SNAPSHOT` archive in the target directory, and produce a `obfuscated.jar` from it. This archive does **not** contain any dependencies (as would be expected).

Further you can not change your configuration like so:
```xml
<inoutpair in="${project.basedir}/yGuardBoilerplate.jar" out="${basedir}/obfuscated.jar" resources="copy" />
```

The `maven-assembly-plugin` will create an assembly, which is a multi-release JAR. This is explicitly noted to be incompatible with [yGuard](https://yworks.github.io/yGuard/compatibility/), and will crash the Shrinker upon usage. However, we have decided to introduce a improved error reporting about multi-release JARs in the upcoming 3.0 release.

What you would like to accomplish is a multi-stage build:

- build an archive (or directory) containing your classes
- obfuscate classes using yGuard
- package the resulting archive / directory using your method of choice

You can find inspiration on how to do this in [our processing example](https://github.com/yWorks/yGuard/tree/master/examples/processing).
I hope this helps and resolves the ticket.

All the best
