### ISSUE TITLE
Fix JavaDoc warnings

### ISSUE THREAD

**Issue by Fohlen** [yWorks/yGuard#77]
Currently there are about 100 JavaDoc warnings generated from our source code. Fix these warnings by properly implementing the comments.

**Comment by just-linux** [comment]
I would like to take this on for Hactoberfest.

**Comment by just-linux** [comment]
I have ran ./gradlew javadoc and I am not seeing the the JavaDoc warnings. If I need to build them another way let me know.

After running ./gradlew clean I ran the following:
(base) john@p7-1297cb:~/Programming/GitHub-repos/yGuard$ ./gradlew javadoc
BUILD SUCCESSFUL in 7s
3 actionable tasks: 3 executed

**Comment by Fohlen** [comment]
Hello there and thanks for taking this on @just-linux 

Running `./gradlew clean javadoc` prints [the following warnings](https://dpaste.org/YGL2) for me.

Iirc if you run `./gradlew build` then JavaDoc is already executed. When you consequently run JavaDoc again, Gradle will notice that it is "UP-TO-DATE", and thus not do anything. Using `clean` before any consequent step should make it work in any case.
Hope that helps!

**Comment by just-linux** [comment]
I will start on the next batch of warnings that showed up when I finished the first 100. This may be a big task since the warnings stop at 100.

**Comment by Fohlen** [comment]
@just-linux please follow our contribution guidelines and:

- create **one** pull request / branch per issue. I can recommend using [GitHub Desktop](https://desktop.github.com/) or comparable software to manage your clone of yGuard
- make sure the tests are passing. your proposed changes break our CI (see https://github.com/yWorks/yGuard/pull/85/checks?check_run_id=1170301132)

**Comment by Hassan-Elseoudy** [comment]
Fixed, please have a look at #91 @Fohlen :)
Have a good day.

**Comment by Fohlen** [comment]
Hey @Hassan-Elseoudy 
Your PR looks really good!
I will try to review it before October 31 so it will count towards your #hacktoberfest contributions.
All the best,

Lenny

**Comment by Hassan-Elseoudy** [comment]
Looking forward for your review.
Enjoy your day
