### ISSUE TITLE
How to obfuscate methods and class names?

### ISSUE THREAD

**Issue by risharde** [yWorks/yGuard#90]
Hi guys, very new to yGuard. I finally got it going with the following xml but I notice that yGuard doesn't change methods, class names etc. I'm wondering if I over expected from this obfuscator. Can you HOW to automatically obfuscate methods, class names etc. I've used "Java Decompiler" and noticed that my method names are seen in plain sight. Also obfuscation strings should be something you guys should seriously be thinking about.

Desperate to get this going. Please advise. Thanks

`    <target depends="compile" name="yguard">
      <taskdef name="yguard" classname="com.yworks.yguard.YGuardTask"
      classpath="yguard.jar"/>
      
      <yguard>

        <inoutpair in="dist\main.jar" out="dist\main_obf.jar"/>

        <shrink logfile="shringlog.txt">
          <keep>
            <class classes="protected"
            methods="protected" fields="protected">
            </class>
          </keep>
        </shrink>

        <rename mainclass="app.main" logfile="renamelog.txt">
          <property name="error-checking" value="pedantic"/>

          <keep>
            <class classes="protected"
            methods="protected" fields="protected">

            </class>
          </keep>
        </rename>

      </yguard>

    </target>	`

**Comment by yGuy** [comment]
Because you told it to do so:
````
<keep>
        <class classes="protected"
        methods="protected" fields="protected">

        </class>
</keep>
```
