### ISSUE TITLE
[ant:shrink] ERROR: Illegal char <:> at index 2: /C:/absolute-path-to-jar-file

### ISSUE THREAD

**Issue by hwcconde** [yWorks/yGuard#93]
Hello,

Sorry if it's a basic question but I've been unable to find it.

I'm following https://github.com/yWorks/yGuard/blob/master/examples/library/build.gradle

I need to specify the path to my jar file, so I changed line 44 to say:
`def archivePath = "relative-path-to-jar-file"`

Then when I try to execute the task I find the error
`[ant:shrink] ERROR: Illegal char <:> at index 2: /C:/absolute-path-to-jar-file`

I'm puzzled as I have passed a relative path but it seems first to expand to a correct, absolute path and then fail due to the Windows syntax for path.

How can I solve it?

**Comment by Fohlen** [comment]
Hey @hwcconde this issue has indeed already been addressed and a fix will arrive in the `3.0.0` release. We would like to ask your to be patient until this release has landed on Maven Central. In the meantime you could use the `master` branch of yGuard already, which contains the necessary fixes.
