### ISSUE TITLE
('Unrecognized bootstrap method: scala/runtime/LambdaDeserialize#bootstrap(...)') occured during the remapping

### ISSUE THREAD

**Issue by serega-upgini** [yWorks/yGuard#99]
Hi, trying to obfuscate scala app, here is my gradle snippet:
```gradle
rename(mainclass: 'org.SearchAgentServer', logfile: "${buildDir}/yguard.log.xml") {
                keep {
                    'package' {
                        patternset {
                            include(name: "scala.*")
                            include(name: "org.*")
                        }
                    }
                }
                property(name: "error-checking", value: "pedantic")
            }
```
the idea is to obfuscate only app classes and do nothing with the rest.
I get exception. Why does yGuard tries to do smth with class from scala package? It's marked as 'keep"
```
Caused by: : yGuard encountered an IO problem!
        at com.yworks.yguard.ObfuscatorTask.execute(ObfuscatorTask.java:1093)
        at com.yworks.yguard.YGuardTask.execute(YGuardTask.java:118)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:80)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.doInvokeMethod(BasicAntBuilder.java:107)

Caused by: java.io.IOException: An error ('Unrecognized bootstrap method: scala/runtime/LambdaDeserialize#bootstrap(...)') occured during the remapping! See the log!)
        at com.yworks.yguard.obf.GuardDB.remapTo(GuardDB.java:547)
        at com.yworks.yguard.ObfuscatorTask.execute(ObfuscatorTask.java:1064)


```

**Comment by Fohlen** [comment]
Hey @serega-upgini this issue happens because you are trying to remap a `invokedynamic` structure that is not included in the JRE. This is most likely caused because Scala includes such instructions. Please see [our documentation](https://yworks.github.io/yGuard/compatibility/#compatibility-to-3rd-party-jvm) on how `invokedynamic` is handled in yGuard. Currently Scala features are not supported, because we do not have someone with in-depth Scala experience in our team. If you would like to contribute Scala support, please let us know (we might also implement it for your corporation if you can cover development costs).

**Comment by serega-upgini** [comment]
Hi @Fohlen , thanks for your response. We need to think about your proposals. For now Im' a bit puzzled. Config excludes all scala and org classes. Why does yGuard still try to do smth with scala classes?

**Comment by Fohlen** [comment]
Hey serega,I'm afraid the matter is a bit more complex. Imagine you obfuscate a class which is not scala and then call that class from your scala code. yGuard will need to evaluate all invocations to resolve the calls to the renamed class in order for the code to work.If however your scala code does not require to call any of the obfuscated code or vice-versa you can try following the processing example. This will isolate scala code from the rest of the archive thus preventing any potential problems with byte code incompatibility. Hope this helps.Am 07.02.2021 20:29 schrieb serega-upgini <notifications@github.com>:
Hi @Fohlen , thanks for your response. We need to think about your proposals. For now Im' a bit puzzled. Config excludes all scala and org classes. Why does yGuard still try to do smth with scala classes?

**Comment by serega-upgini** [comment]
Thanks for your explanation.
